# auto-generated by schedule-loadtest.ps1
$K6     = 'C:\tools\k6\k6.exe'
$Script = 'D:\drive_files\10.worksfree\load-test\nas-load-test.js'
$LogDir = 'D:\drive_files\10.worksfree\load-test'

$ReportTs = Get-Date -Format "yyyyMMdd-HHmm"
$LogFile  = Join-Path $LogDir "report-$ReportTs.txt"
$JsonFile = Join-Path $LogDir "report-$ReportTs.json"

"[START] WorksFree NAS Load Test: " + (Get-Date) | Out-File $LogFile -Encoding utf8

& $K6 run --env TARGET_URL=http://192.168.100.38:8082 --env STEP_VUS=10 --env STEP_HOLD=60 --env MAX_VUS=200 --env P95_LIMIT=3000 $Script 2>&1 | Tee-Object -FilePath $LogFile -Append

$JsonSrc = Join-Path (Get-Location) "nas-load-test-report.json"
if (Test-Path $JsonSrc) { Move-Item $JsonSrc $JsonFile -Force }

"[END] Test complete: " + (Get-Date) | Out-File $LogFile -Append -Encoding utf8
Write-Host "Report saved: $LogFile"
