# schedule-loadtest.ps1
# WorksFree Hub NAS Load Test Scheduler
#
# Usage:
#   .\schedule-loadtest.ps1              # default 02:00
#   .\schedule-loadtest.ps1 -RunAt 08:00
#   .\schedule-loadtest.ps1 -RunAt 14:30
#
# Run as Administrator

param(
    [string]$RunAt = "02:00"
)

# ── Config ───────────────────────────────────────────────────────────
# NAS port mapping (Cloudflare origin):
#   :8081 -> test
#   :8080 -> staging
#   :8082 -> www (production)
#
# Direct NAS test (bypasses Cloudflare CDN cache)
$NasTargetUrl = "http://192.168.100.38:8082"   # www (default)
# $NasTargetUrl = "http://192.168.100.38:8080"  # staging
# $NasTargetUrl = "http://192.168.100.38:8081"  # test

$StepVUs      = 10
$StepHoldSec  = 60
$MaxVUs       = 200
$P95LimitMs   = 3000
$TaskName     = "WF-NAS-LoadTest"
# ─────────────────────────────────────────────────────────────────────

if ($RunAt -notmatch '^\d{2}:\d{2}$') {
    Write-Host "ERROR: -RunAt must be HH:mm format (e.g. 08:00, 14:30)" -ForegroundColor Red
    exit 1
}

$ScriptDir  = Split-Path -Parent $MyInvocation.MyCommand.Path
$TestScript = Join-Path $ScriptDir "nas-load-test.js"
$RunScript  = Join-Path $ScriptDir "run-load-test.ps1"

# Locate k6
$k6Cmd  = Get-Command k6 -ErrorAction SilentlyContinue
$K6Path = if ($k6Cmd) { $k6Cmd.Source } else { $null }
if (-not $K6Path) {
    $fb = "C:\tools\k6\k6.exe"
    if (Test-Path $fb) { $K6Path = $fb }
}
if (-not $K6Path) {
    Write-Host "k6 not found. Install: https://github.com/grafana/k6/releases" -ForegroundColor Red
    exit 1
}

Write-Host "k6 found: $K6Path" -ForegroundColor Green

# ── Generate run-load-test.ps1 ───────────────────────────────────────
# Build k6 command line using concatenation to avoid & inside double-quoted string
$k6Args = "--env TARGET_URL=$NasTargetUrl --env STEP_VUS=$StepVUs --env STEP_HOLD=$StepHoldSec --env MAX_VUS=$MaxVUs --env P95_LIMIT=$P95LimitMs"
$k6Line = '& $K6 run ' + $k6Args + ' $Script 2>&1 | Tee-Object -FilePath $LogFile -Append'

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# auto-generated by schedule-loadtest.ps1")
$lines.Add("`$K6     = '$K6Path'")
$lines.Add("`$Script = '$TestScript'")
$lines.Add("`$LogDir = '$ScriptDir'")
$lines.Add("")
$lines.Add('$ReportTs = Get-Date -Format "yyyyMMdd-HHmm"')
$lines.Add('$LogFile  = Join-Path $LogDir "report-$ReportTs.txt"')
$lines.Add('$JsonFile = Join-Path $LogDir "report-$ReportTs.json"')
$lines.Add("")
$lines.Add('"[START] WorksFree NAS Load Test: " + (Get-Date) | Out-File $LogFile -Encoding utf8')
$lines.Add("")
$lines.Add($k6Line)
$lines.Add("")
$lines.Add('$JsonSrc = Join-Path (Get-Location) "nas-load-test-report.json"')
$lines.Add('if (Test-Path $JsonSrc) { Move-Item $JsonSrc $JsonFile -Force }')
$lines.Add("")
$lines.Add('"[END] Test complete: " + (Get-Date) | Out-File $LogFile -Append -Encoding utf8')
$lines.Add('Write-Host "Report saved: $LogFile"')

[System.IO.File]::WriteAllLines($RunScript, $lines, [System.Text.UTF8Encoding]::new($true))
Write-Host "Run script generated: $RunScript" -ForegroundColor Green

# ── Schedule ─────────────────────────────────────────────────────────
$today     = Get-Date
$runAtTime = [datetime]::ParseExact($today.ToString("yyyy-MM-dd") + " $RunAt", "yyyy-MM-dd HH:mm", $null)
if ($runAtTime -le $today) {
    $runAtTime = $runAtTime.AddDays(1)
    Write-Host "Time $RunAt already passed -> scheduled for tomorrow $RunAt" -ForegroundColor Yellow
}

$action   = New-ScheduledTaskAction -Execute "powershell.exe" -Argument "-NonInteractive -ExecutionPolicy Bypass -File `"$RunScript`"" -WorkingDirectory $ScriptDir
$trigger  = New-ScheduledTaskTrigger -Once -At $runAtTime
$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Hours 3) -StartWhenAvailable

try {
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -RunLevel Highest -Force -ErrorAction Stop | Out-Null

    Write-Host ""
    Write-Host "======================================================" -ForegroundColor Cyan
    Write-Host "  Scheduled successfully" -ForegroundColor Cyan
    Write-Host "======================================================" -ForegroundColor Cyan
    Write-Host "  Time       : $($runAtTime.ToString('yyyy-MM-dd HH:mm'))" -ForegroundColor White
    Write-Host "  Target URL : $NasTargetUrl" -ForegroundColor White
    Write-Host "  Max VU     : $MaxVUs (step $StepVUs)" -ForegroundColor White
    Write-Host "  P95 limit  : ${P95LimitMs}ms" -ForegroundColor White
    Write-Host "  Task name  : $TaskName" -ForegroundColor White
    Write-Host "  Report dir : $ScriptDir\report-*.txt" -ForegroundColor White
    Write-Host "======================================================" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "  Cancel : Unregister-ScheduledTask -TaskName '$TaskName' -Confirm:`$false"
    Write-Host "  Run now: & '$RunScript'"
} catch {
    Write-Host "Failed to register task (requires Administrator)" -ForegroundColor Red
    Write-Host "  Error: $_" -ForegroundColor Red
}